### ISSUE TITLE
Names of functions

### ISSUE THREAD

**Issue by rricard** [tc39/proposal-change-array-by-copy#10]
See https://github.com/tc39/proposal-record-tuple/issues/121, but we might want to discuss naming before commiting to this.

**Comment by acutmore** [comment]
Some data that could feed into this discussion.

Kotlin has
`array.sort()` (mutating)
`array.sorted()` (non-mutating)

Java has
`Arrays.sort(array)` (mutating)
`stream.sorted()` (non-mutating)

Python has
`arr.sort()` (mutating)
`sorted(arr)` (non-mutating)

Swift has
`arr.sort()` (mutating)
`arr.sorted()` (non-mutating)

**Comment by bmeck** [comment]
Just to be clear, using past participles makes conversation hard: E.G. "I popped the array." has a fairly easy to understand meaning currently but with different phrasing with past participles it could suddenly mean either the mutating or non-mutating method, which potentially even have differing return expectations.

**Comment by arxpoetica** [comment]
Definitely prefer something that reads different enough for scanning purposes:

```
Tuple.prototype.copyPush (vs. .pushed)
Tuple.prototype.copyPop (vs. .popped)
Tuple.prototype.copyReverse (vs. .reversed)
```

vs. just past tense adding `ed`

**Comment by acutmore** [comment]
From an autocomplete perspective it looks like having a common prefix instead of a suffix will not impact discoverability 👍 

<img width="500" alt="screenshot showing autocomplete for both reverse and copyReverse after typing in list.reverse" src="https://user-images.githubusercontent.com/4369552/115453171-3b6ed980-a217-11eb-9d9e-bdacd3d6c299.png">

**Comment by rricard** [comment]
We will introduce `with<PastTense>` as the new naming scheme as described in #26. This choice can be discussed here.

**Comment by rauschma** [comment]
I like the new scheme! Maybe the past tense isn’t even needed:

* `.withFill`
* `.withCopyWithin`
* `.withPop`
* `.withPush`
* `.withReverse`
* `.withShift`
* `.withSort`
* `.withSplice`
* `.withUnshift`
* `.withAt`

Upside: Easier to derive the names (which sound more familiar). Downside: Doesn’t map as well to natural language.

**Comment by rauschma** [comment]
Without past tense, the rules are simpler – just prefix “with”.

With past tense, you have to look for a verb (which may or may not be there) and then change it to past tense.

I’m also not completely sure that the past is really closer to natural language.

**Comment by acutmore** [comment]
Something else to discuss: If we do for the `withAt(index, value)` method should the arguments be flipped to `withAt(index, value)`? The rationale being folk could remember the arg order with the phrase "with (value) At (index)"

**Comment by rricard** [comment]
Yea, I think we should more change `withAt` to something else than the other way around if we want to address this

**Comment by acutmore** [comment]
One idea I had was `withReplaced(index, value)` - this may also make it clearer that the index must fall within the existing length, unlike direct index assignment.

**Comment by Alhadis** [comment]
IMHO, this is a mistake. Parity with a deliberately-immutable data structure (Tuples) isn't worth the confusing and inconsistent plethora of new methods. Here's our current list of array-returning verbs:
 
| Method                            | Modifies receiver?     |
|:----------------------------------|:-----------------------|
| `Array.prototype.concat()`        | ✅
| `Array.prototype.copyWithin()`    | ✅
| `Array.prototype.fill()`          | ✅
| `Array.prototype.filter()`        |
| `Array.prototype.flat()`          |
| `Array.prototype.flatMap()`       |
| `Array.prototype.map()`             |
| `Array.prototype.pop()`           | ✅
| `Array.prototype.push()`          | ✅
| `Array.prototype.reverse()`       | ✅
| `Array.prototype.shift()`         | ✅
| `Array.prototype.slice()`         |
| `Array.prototype.sort()`          | ✅
| `Array.prototype.splice()`        | ✅
| `Array.prototype.unshift()`       | ✅

You really want to add another ~10 methods to that list _just_ to be consistent with an unrelated but superficially-similar object type? I'd rather stick with the familiar `.slice().avoidModifyingOriginal()` idiom to operate upon a copy of an array I don't want modified. This, combined with `Array.from(foo)` or even just `[...foo]`, pretty much covers every use-case I can think of which this proposal advertises (even with frozen arrays).

> This proposal notably makes it easier to write code able to deal with Arrays and Tuples interchangeably.

This strikes me as a non-argument. Sure, they're both iterable and array-ish, but so are TypedArrays. A `Uint8Array` doesn't have `.pop()` or `.push()` methods, because it's fixed-length. It does, however, have methods to construct another of its kind via `.map()` or `.filter()`. Such a discrepancy won't look out-of-place on `Tuple.prototype`, either. Conversely, a bunch of (really misleading) methods on `Array.prototype` isn't adding anything other than autocomplete pollution.

Moreover, how many users will need to construct tuples from other tuples often enough to justify the existence of a .`pop()` (or `.popped()`, `.aufgetaucht()`, whatever) method? Be honest.

**Comment by acutmore** [comment]
Hi @Alhadis, this issue is focused more on the naming of the methods. #27 is for discussing reducing the number of new methods.

**Comment by Alhadis** [comment]
I must've paraphrased out the part of my comment that explicitly addresses the naming. Use methods named after their equivalent operations on `Array.prototype`. Developers will know what `Tuple.prototype.fill` does from the name alone—the fact that tuples are immutable structures by definition makes the _"returning a copy"_ part of the methods implicit.

As for methods that don't sanely carry across to tuples (`.pop()`, `.shift()`, et al), I'd leave 'em out, honestly. If you find `Tuple.from([...otherTuple, newValues])` too verbose, use different verbs:

~~~js
Array.prototype.unshift => Tuple.prototype.prepend
Array.prototype.push    => Tuple.prototype.append
Array.prototype.pop     => Tuple.prototype.slice(-1)
Array.prototype.shift   => Tuple.prototype.slice(1)
~~~

I doubt the last two operations will be common enough to warrant their own methods.

**Comment by papb** [comment]
[Quoting myself from the other issue](https://github.com/tc39/proposal-record-tuple/issues/121#issuecomment-668636727):

> My personal favorites for now are the `.copy*` names, such as `.copyPush`, `.copyReverse`, etc. What can I do to improve the odds of these names being chosen?

(about one year later, these are still my favorites)

**Comment by papb** [comment]
@Alhadis `prepend` and `append` still carry the idea of mutation to me.

**Comment by Alhadis** [comment]
@papb What are your thoughts on `sort` and `reverse`, then?

**Comment by papb** [comment]
> @papb What are your thoughts on `sort` and `reverse`, then?

They also carry the idea of mutation to me. For the immutable counterparts, I would suggest `.copySort()` and `.copyReverse()`. Is this what you asked? Sorry if I misunderstood.

**Comment by omeid** [comment]
I think going with the simple past tense and consistent with other languages is a not a bad idea at all.

I am not convinced that scanning is an issue, once you're familiar with these methods it is not hard to look out for them sense you will just scan for `yyyy.XX__d(....)` vs `yyyy.XX__[^d](....)` .

**Comment by OmgImAlexis** [comment]
Personally if I saw "with" I'd expect to need to pass a function not that it was in past tense.

**Comment by mohsen1** [comment]
Maybe because I'm not a native English speaker I had this impression but `with*` didn't convey the meaning of those functions to me. `.sorted` does.

**Comment by papb** [comment]
> `array.sorted()` I expect this not to mutate but instead return a new array.

@OmgImAlexis I don't... I expect `array.sorted()` to do exactly the same as `array.sort()`. That's why I think a clearer name would be beneficial.

**Comment by acutmore** [comment]
'with' is not the only prefix we are considering. 'copy' was also suggested.  `.copySorted()`  `.copySliced()` `copyPopped()`, though `.copyCopiedWithin` may not be a good fit.

**Comment by acutmore** [comment]
Another suggestion was 'to', similar to `String.prototype.toUpperCase()`. `.toSorted()`  `.toSliced()`  `.toPopped(), `toCopiedWithin()`

**Comment by ljharb** [comment]
I like that, it definitely strongly implies a conversion - even if only from one array to another.

**Comment by zloirock** [comment]
`to` is much better than `with`.

**Comment by rauschma** [comment]
I also like that `to` implies conversion. Downside: Already an established prefix (`.toString()`, `.toJSON()`, etc.).

Maybe `as`? `.asSorted() .asSliced() .asPopped(), asCopiedWithin()`

**Comment by ljharb** [comment]
That existing usage is why i like it - toString and toJSON produce a new value, and the name tells you what it is.

**Comment by arxpoetica** [comment]
Fan of `to`. Semi-familiar convention.

**Comment by Nixinova** [comment]
How about being explicit with `popNew()` `unshiftNew()` etc? I don't think just adding `-ed` is a good idea as it seems way too close to the normal form and that may just create another confusing slice/splice-type scenario (would would be worsened if `spliced` was added...)

**Comment by jakehamilton** [comment]
I think it's important for these names to be familiar coming from the mutating versions while also making it clear there is a new copy of the array being created. Since I don't think it's been mentioned, I'd like to suggest `clone*` as a pattern for these functions. For example: `cloneSorted`, `cloneReversed`

Do note that this suggestion does not make a distinction between things like `cloneSorted` and `cloneSort`, only that the function name begins with "clone".

**Comment by phryneas** [comment]
Another naming scheme that would make the purpose of these functions stand out more might be a prefix of `immutable`, or short `immut`.

Just throwing that one in the ring :)

**Comment by dkns** [comment]
As a non-native english speaker 'withX' is hard to intuitively understandp; much harder than 'copyX' or 'toX'.

**Comment by timoxley** [comment]
Putting a vote in for `toX` or `copyX` instead of `withX`.

`toX` at least has some precedent in `toString`, `toArray`, yeah they're changing types but it's unambiguous and clear. The closest thing to `withX` is probably `copyWithin`? and the `within` part actually helps to communicates that it  mutates, and here the `with` is trying to communicate that it doesn't mutate. Yes, `within` is a different word to `with` but I think it's similar enough in meaning and appearance to make you pause for a moment to remember whether it's trying to say it's mutating or not mutating. Like many people I struggled for a long time to remember which was which with `splice` vs `slice`, so IMO it'd be good to avoid doing that to people again.

**Comment by WebReflection** [comment]
Agreeing with [this comment](https://github.com/tc39/proposal-change-array-by-copy/issues/10#issuecomment-853000833), and also with either `as` or `to` as prefix, where both do a better job than using `with`.

> E.G. "I popped the array." has a fairly easy to understand meaning

And so does *I have assigned the tuple as popped one*.

**Comment by Rich-Harris** [comment]
Except in contrived cases, 'with' always implies the _addition_ of something. It's therefore a confusing choice for methods that _remove_ elements — `withPopped` suggests we're... adding the popped element? Perhaps this is the rare case where a native English speaker is at a disadvantage in programming, but my brain would get tied in knots trying to understand the return value of these methods.

`to` is a better prefix, as has been noted, but it forces the use of the past tense which I think is unfortunate on two grounds. Firstly, it moves the focus to the _element_ rather than the _array_. (You don't pop an array, you pop an element _from_ the array, or at least that's my understanding of the semantics.) `toPopped` to my mind is ambiguous — we could be changing the array _to_ the array minus the popped element, or we could be converting from the array _to_ the popped element.

Secondly, it introduces an asymmetry — the past tense of `splice` adds a `d`, the past tense of `sort` adds an `ed`, the past tense of `pop` adds `ped`. Converting between mutative and non-mutative method names is therefore not a mechanical process, and it's honestly just less aesthetically pleasing. 

I propose the following scheme:

* Array.prototype.postFill(value, start, end) -> Array
* Array.prototype.postCopyWithin(copiedTarget, start, end) -> Array
* Array.prototype.postPop() -> Array
* Array.prototype.postPush(values...) -> Array
* Array.prototype.postReverse() -> Array
* Array.prototype.postShift() -> Array
* Array.prototype.postSort(compareFn) -> Array
* Array.prototype.postSplice(start, deleteCount, ...items) -> Array
* Array.prototype.postUnshift(...values) -> Array
* Array.prototype.postUpdate(index, value) -> Array

The odd one out here is `withAt` -> `postUpdate`, since `postAt` doesn't make any more sense than `withAt`.

**Comment by mjr** [comment]
Wouldn't something like python be a good option?

Python
```python
array.sort() # (mutating)
sorted(array) # (non-mutating)

array.reverse() # (mutating)
reversed(array) # (non-mutating)
```

Javascript
```javascript
array.sort() // (mutating)
Array.sorted(array) // (non-mutating)

array.reverse() // (mutating)
Array.reversed(array) // (non-mutating)
```

**Comment by Rich-Harris** [comment]
`Array.sorted(x)` is 15 characters, `x.toSorted()` or `x.postSort()` is 12. What do you gain in return for the extra characters?

**Comment by mjr** [comment]
There is no gain in this regard, i just suggested it to see what you think about this option.

**Comment by OrenMe** [comment]
Is it possible to do the same as it was done with addEventListener and add an options object to the method that will allow to specify the operation type of it if it is mutating or not? I know it will change the response according to mode but this can be expected with regards of setting the option object.
This will also allow future expansion of features to the method like maybe returning sealed object or other actions and response types.

**Comment by lightmare** [comment]
For me
- `withXY` doesn't evoke the intended meaning at all.
- `toXY` is better, but `to_Verb_` is a bit confusing (both `toString` and `toJSON` are `to_Noun_`).
- `copyXY` is clear.

`withAt` is a bad name regardless of the prefix. The method `.at` is already non-mutating, and doesn't throw when index is out of range. Better pick a different name. Or drop this one, `copySpliced(index, index+1, value)` can do the job. In a scenario where `withAt` would be used a lot, the Array could likely be replaced with Tuple, anyway.

Naming aside, I don't see the benefit of putting `__Sorted()` and `__Reversed()` on the prototype. Depending on the chosen prefix, all it would do is save 2-4 characters over `a.slice().sort()` and the like.

I mean, if saving 2-4 characters is considered worth it, then `Array.sorted(a)` would save 5 characters over `Array.from(a).sort()`, and would be more useful, as it would work with any iterable or array-like object, unlike `[...a].sort()` or `a.copySorted()`.

Out of the proposed methods, only `a.copySpliced()` seems useful to me, but many of its use cases could be covered by proper slicing syntax, which JS currently lacks.

**Comment by WebReflection** [comment]
> So list.nonMutatingSort() would work regardless of the type of list. This wouldn't be achieved with static type specific methods on the separate constructors.

that's true for `Array.from` and derivatives too though, yet it makes it clear the intent to create a *new* collection, given a specific input.

I actually think the Python *ish* suggestion wins over all others .. the `Array.prototype` is stuffed already, and methods like `copySorted(fn)` feel lame, compared to `Array.sort(arr, fn)`, or even `Array.sorted(...)`.

imho, the requirements are clear, the way forward looks already overly confusing to me.

**Comment by AnthonyLenglet** [comment]
Putting in a vote for `to` here, it is definitely better than `with`, since its already used to convey a transformation without modification in other cases like `toString` and `toJSON`

only problem is `<array>.toAt`, which just looks really odd and isn't the most explicit, not sure how that could be handled

also, a bit about the proposal of the word `copy`, it actually makes the `at` problem even worse

```js
const array = [1, 5, 10];
const newArray = array.copyAt(1, 2);
console.log(newArray); // one could think this should return [1, 10, 10], but this is actually [1, 2, 10]
```

**Comment by acutmore** [comment]
Thanks for your input @AnthonyLenglet.

I think it can be an option for the `withAt` functionality to have a name that does not follow the same pattern as the other 3 new methods. The other methods are all non-mutating equivalents of existing methods, whereas `withAt` can be viewed as the non mutating form of the assignment operation `list[index] = value`.

**Comment by zloirock** [comment]
@rricard @acutmore hey, do you plan to change names before the TC39 meeting? It seems that almost no one likes `with`, but `to` is not so bad.

**Comment by acutmore** [comment]
Hi @zloirock , the key goal of the next Tc39 meeting for us is to get volunteers to review the spec. We will mention that the current names are still very much tbc. But I don’t think we need to update the documents until the new names have been agreed.
